import {
  MagnifyingGlass,
  MagnifyingGlassSelected,
  Lightbulb,
  LightbulbSelected,
  SwissArmy,
  SwissArmySelected,
  File,
  FileSelected,
  Smiley,
  SmileySelected,
} from './assets';

export const cards = [
  {
    key: 1,
    icon: Lightbulb,
    iconSelected: LightbulbSelected,
    altText: 'lightbulb',
    textContent: 'Estimula a criatividade',
    selected: false,
  },
  {
    key: 2,
    icon: MagnifyingGlass,
    iconSelected: MagnifyingGlassSelected,
    altText: 'magnifying-glass',
    textContent: 'Estimula a curiosidade',
    selected: false,
  },
  {
    key: 3,
    icon: SwissArmy,
    iconSelected: SwissArmySelected,
    altText: 'swiss-army',
    textContent: 'Se adapta à necessidade',
    selected: false,
  },
  {
    key: 4,
    icon: File,
    iconSelected: FileSelected,
    altText: 'file',
    textContent: 'Ótima didáctica',
    selected: false,
  },
  {
    key: 5,
    icon: Smiley,
    iconSelected: SmileySelected,
    altText: 'smiley',
    textContent: 'Gente boasíssima',
    selected: false,
  },
];
